name=input("Enter your name: ")
age=int(input("Enter yuor age: "))
gender=input("Enter your gender: ")
height=float(input("Enter yor height: "))
weight=int(input("Enter your weight: "))
school=input("Enter your school name: ")
father_name=input("Enter your Father's name: ")
mother_name=input("Enter your Mother's name: ")
hobby=input("Enter your hobby: ")
nationality=input("Enter your Nationality: ")
print("Name: ",name)
print("Age: ",age)
print("Gender: ",gender)
print("Height: ",height,"ft")
print("Weight: ",weight,"kg")
print("School name: ",school)
print("Father's name: ",father_name)
print("Mother's name: ",mother_name)
print("Hobby: ",hobby)
print("Nationality: ",nationality)